### ISSUE TITLE
Crash on subtly invalid from_bin input

### ISSUE THREAD

**Issue by jtippett** [libitx/eddy#1]
Hey there, great library! I did notice one issue. Due to an invalid encoding setting in one system, I was passing jumbled keys around, and eddy crashed hard:
```
iex(5)> b64_vk = "AjXhpbLYvvzkWnNjSWocHAtWS/eokEsCkVTSm08gLfKL"
"AjXhpbLYvvzkWnNjSWocHAtWS/eokEsCkVTSm08gLfKL"
iex(6)> {:ok, bin} = Base.decode64 b64_vk
{:ok,
 <<2, 53, 225, 165, 178, 216, 190, 252, 228, 90, 115, 99, 73, 106, 28, 28, 11,
   86, 75, 247, 168, 144, 75, 2, 145, 84, 210, 155, 79, 32, 45, 242, 139>>}
iex(7)> Eddy.PubKey.from_bin bin
** (FunctionClauseError) no function clause matching in Eddy.Serializable.Encoder.Eddy.Point.normalize_y/1    
    
    The following arguments were given to Eddy.Serializable.Encoder.Eddy.Point.normalize_y/1:
    
        # 1
        <<2, 53, 225, 165, 178, 216, 190, 252, 228, 90, 115, 99, 73, 106, 28, 28, 11,
          86, 75, 247, 168, 144, 75, 2, 145, 84, 210, 155, 79, 32, 45, 242, 139>>
    
    Attempted function clauses (showing 1 out of 1):
    
        defp normalize_y(<<bytes::binary-size(31), last>>)
    
    (eddy 1.0.0) lib/eddy/point.ex:120: Eddy.Serializable.Encoder.Eddy.Point.normalize_y/1
    (eddy 1.0.0) lib/eddy/point.ex:99: Eddy.Serializable.Encoder.Eddy.Point.parse/2
    (eddy 1.0.0) lib/eddy/pub_key.ex:27: Eddy.Serializable.Encoder.Eddy.PubKey.parse/2
    (eddy 1.0.0) lib/eddy/pub_key.ex:24: Eddy.PubKey.from_bin/2
    iex:7: (file)
```

Probably because the key was the right "shape" but due to the aforementioned settings issue, it evidently made it through whatever checks were in place. It's no issue as I am further validating the data and also placing the from_bin in a try/catch but since it was a pretty hard crash, thought I'd let you know.

Thanks again for the great library, a joy to work with!

**Comment by libitx** [comment]
I see. So the key was wrong (it's 33 bytes), but expected behaviour of `Eddy.PubKey.from_bin` would be to return an `{:error, useful_term}` tuple, not raise as it's doing. Is that about right?

**Comment by jtippett** [comment]
I think the expected behaviour is to return an error tuple, yes. The behaviour is inconsistent:

```
iex(67)> Eddy.PubKey.from_bin("1234567890123456789012345678901")
{:error, {:decode_error, "invalid point length"}}
iex(68)> Eddy.PubKey.from_bin("12345678901234567890123456789012")
{:ok,
 %Eddy.PubKey{
   point: %Eddy.Point{
     x: 15210286179116880499108877439899788040423458621963594945337907680618980329860,
     y: 22702550761799267355187145649125784605216755694630776232256222584591002841649
   }
 }}
iex(69)> Eddy.PubKey.from_bin("123456789012345678901234567890123")
** (FunctionClauseError) no function clause matching in Eddy.Serializable.Encoder.Eddy.Point.normalize_y/1    
    
    The following arguments were given to Eddy.Serializable.Encoder.Eddy.Point.normalize_y/1:
    
        # 1
        "123456789012345678901234567890123"
    
    Attempted function clauses (showing 1 out of 1):
    
        defp normalize_y(<<bytes::binary-size(31), last>>)
    
    (eddy 1.0.0) lib/eddy/point.ex:120: Eddy.Serializable.Encoder.Eddy.Point.normalize_y/1
    (eddy 1.0.0) lib/eddy/point.ex:99: Eddy.Serializable.Encoder.Eddy.Point.parse/2
    (eddy 1.0.0) lib/eddy/pub_key.ex:27: Eddy.Serializable.Encoder.Eddy.PubKey.parse/2
    (eddy 1.0.0) lib/eddy/pub_key.ex:24: Eddy.PubKey.from_bin/2
    iex:69: (file)
```

Like I said, this was completely my fault, but i was still a little surprised since it validates under length, but blows up on over length. Just thought I'd let you know! Cheers
